// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHrhqSo9A593YNoK3WC-Dl1Y6BCoSsuPg',
    appId: '1:551765794497:web:6afd331fd0746c6985be40',
    messagingSenderId: '551765794497',
    projectId: 'flutter-chat-ca79d',
    authDomain: 'flutter-chat-ca79d.firebaseapp.com',
    storageBucket: 'flutter-chat-ca79d.appspot.com',
    measurementId: 'G-KZ56KWSJPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDZUBDdWEMNbzWLl2zAKoyaDA8JzZL4P0',
    appId: '1:551765794497:android:1947493b3c29cdba85be40',
    messagingSenderId: '551765794497',
    projectId: 'flutter-chat-ca79d',
    storageBucket: 'flutter-chat-ca79d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqRQq6qmmAOV9Bn3CKmqMBL8KPJw8iL54',
    appId: '1:551765794497:ios:82158f006cf1512885be40',
    messagingSenderId: '551765794497',
    projectId: 'flutter-chat-ca79d',
    storageBucket: 'flutter-chat-ca79d.appspot.com',
    iosClientId:
        '551765794497-c9rlobk3t4ndha3d8823aisjj5a6jobv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqRQq6qmmAOV9Bn3CKmqMBL8KPJw8iL54',
    appId: '1:551765794497:ios:82158f006cf1512885be40',
    messagingSenderId: '551765794497',
    projectId: 'flutter-chat-ca79d',
    storageBucket: 'flutter-chat-ca79d.appspot.com',
    iosClientId:
        '551765794497-c9rlobk3t4ndha3d8823aisjj5a6jobv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
